In [1]:
import konlpy

In [2]:
import pandas as pd
from math import log

In [3]:
docs=[
    '기본적인 언어 파이썬',
    '기본적인 문법 언어 자바',
    '자바 언어 객체 지향',
    '언어 문법 어려움'
]

In [31]:
voc=list(set([w for doc in docs for w in doc.split()]))

In [32]:
voc

['자바', '언어', '객체', '파이썬', '기본적인', '지향', '문법', '어려움']

In [28]:
n=len(docs)

In [34]:
def tf(term, doc):
    return doc.count(term)
def idf(term):
    df=0
    for doc in docs:
        df += term in doc 
    return log(n/(df+1))    
def tfidf(term, doc):
    return tf(term, doc)*idf(term)


In [33]:
#DTM(TF)

res=[]
for i in range(n):
    res.append([])
    d=docs[i] #'기본적인 언어 파이썬'
    for j in range(len(voc)):   #8개 단어
        term=voc[j] #['객체', '기본적인', '문법', '어려움', '언어', '자바', '지향', '파이썬']
        res[-1].append(tf(term,d))
        
tf_=pd.DataFrame(res, columns=voc)
tf_


자바  언어  객체  파이썬  기본적인  지향  문법  어려움
0   0   1   0    1     1   0   0    0
1   1   1   0    0     1   0   1    0
2   1   1   1    0     0   1   0    0
3   0   1   0    0     0   0   1    1

In [36]:
#IDF
res=[]
for i in range(len(voc)):
    res.append(idf(voc[i]))

idf_=pd.DataFrame(res, index=voc, columns=['idf'])    
idf_


idf
자바    0.287682
언어   -0.223144
객체    0.693147
파이썬   0.693147
기본적인  0.287682
지향    0.693147
문법    0.287682
어려움   0.693147

In [37]:
#tfidf행렬
res=[]
for i in range(n):
    res.append([])
    doc=docs[i]
    for j in range(len(voc)):
        term=voc[j]
        res[-1].append(tfidf(term, doc))
        
tfidf_=pd.DataFrame(res, columns=voc)
tfidf_


자바        언어        객체       파이썬      기본적인        지향        문법  \
0  0.000000 -0.223144  0.000000  0.693147  0.287682  0.000000  0.000000   
1  0.287682 -0.223144  0.000000  0.000000  0.287682  0.000000  0.287682   
2  0.287682 -0.223144  0.693147  0.000000  0.000000  0.693147  0.000000   
3  0.000000 -0.223144  0.000000  0.000000  0.000000  0.000000  0.287682   

        어려움  
0  0.000000  
1  0.000000  
2  0.000000  
3  0.693147

In [40]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [42]:
vec=CountVectorizer()

In [45]:
vec.fit_transform(docs).toarray()
# vec.vocabulary_

array([[0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 0, 0]], dtype=int64)

In [46]:
tfidfvec = TfidfVectorizer()

In [47]:
tfidfvec.fit_transform(docs).toarray()

array([[0.        , 0.5728925 , 0.        , 0.        , 0.37919167,
        0.        , 0.        , 0.72664149],
       [0.        , 0.53931298, 0.53931298, 0.        , 0.35696573,
        0.53931298, 0.        , 0.        ],
       [0.58783765, 0.        , 0.        , 0.        , 0.30675807,
        0.46345796, 0.58783765, 0.        ],
       [0.        , 0.        , 0.5728925 , 0.72664149, 0.37919167,
        0.        , 0.        , 0.        ]])

In [48]:
tfidfvec.vocabulary_

{'기본적인': 1, '언어': 4, '파이썬': 7, '문법': 2, '자바': 5, '객체': 0, '지향': 6, '어려움': 3}

In [ ]:
#tfidf 활용 : 문서에서 주제어 추출. 유사한 문서 검색

In [51]:
from numpy import dot
from numpy.linalg import norm
import numpy as np
doc1=np.array([0,1,1,1])
doc2=np.array([1,0,1,1])

cos_sim = dot(doc1, doc2) / (norm(doc1)*norm(doc2))

In [50]:
norm(doc1) # doc1 벡터 크기
dot(doc1, doc2) # doc1과 doc2 벡터간 내적

2

In [52]:
cos_sim

0.6666666666666667

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
cosine_similarity([doc1], [doc2])[0][0]

0.6666666666666669

In [58]:
# cosine_similarity(영화1. 영화2, ... 영화n) # 최댓값
df=pd.read_csv('f:/data/metadata/movies_metadata.csv', low_memory=False)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45466 non-null  object 
 1   belongs_to_collection  4494 non-null   object 
 2   budget                 45466 non-null  object 
 3   genres                 45466 non-null  object 
 4   homepage               7782 non-null   object 
 5   id                     45466 non-null  object 
 6   imdb_id                45449 non-null  object 
 7   original_language      45455 non-null  object 
 8   original_title         45466 non-null  object 
 9   overview               44512 non-null  object 
 10  popularity             45461 non-null  object 
 11  poster_path            45080 non-null  object 
 12  production_companies   45463 non-null  object 
 13  production_countries   45463 non-null  object 
 14  release_date           45379 non-null  object 
 15  re

In [61]:
df=df.head(20000)

In [64]:
df['overview']=df['overview'].fillna('')

In [66]:
df[['overview']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   overview  20000 non-null  object
dtypes: object(1)
memory usage: 156.4+ KB


In [67]:
tfidf=TfidfVectorizer(stop_words='english') # 불용어 제거

In [68]:
tfidfm=tfidf.fit_transform(df['overview'])

In [69]:
tfidfm # 2만편의 영화 줄거리에 사용된 unique한 단어의 개수가 47487개 있음
# 20000*47487 행렬이고, 요소의 개수는 5535909개

<20000x47487 sparse matrix of type '<class 'numpy.float64'>'
	with 535909 stored elements in Compressed Sparse Row format>

In [70]:
cos_sim=cosine_similarity(tfidfm, tfidfm) 

In [72]:
cos_sim.shape

(20000, 20000)

In [73]:
cos_sim[0]

array([1.        , 0.01575748, 0.        , ..., 0.        , 0.        ,
       0.        ])